### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by dopiks** [hphde/yeelight-shell-scripts#1]
./yeelight-scene.sh 0 On
./yeelight.sh: 3: ./yeelight.sh: Syntax error: "(" unexpected

`#!/bin/sh`
`declare -a ID=(192.168.1.29 192.168.1.80)`

**Comment by dopiks** [comment]
sh is not bash  )

**Comment by hphde** [comment]
You are right. bash is default for me. Don't know if zsh or ksh can't handle this also

**Comment by hphde** [comment]
fixed
