### ISSUE TITLE
Music mode

### ISSUE THREAD

**Issue by kounelios13** [hphde/yeelight-shell-scripts#12]
Hello . I got my yeelight today. I was wondering If it is possible to use music mode from ubuntu (spotify, youtube etc)

**Comment by hphde** [comment]
AFAIK music mode is just something by using the Smartphone app. The Smartphone receives sound on it's microphone and converts it into light patterns. So nothing to do with setting up the lights itself. That said in theory you could do the same using a computer and convert music into whatever light mode but this is far beyond this rather simple project

**Comment by kounelios13** [comment]
Oh ok thank you.
