### ISSUE TITLE
All Yeelights?

### ISSUE THREAD

**Issue by wowwood** [hphde/yeelight-shell-scripts#2]
Hi,

Is there any way to apply a script to all yeelights at once?

Thanks

**Comment by hphde** [comment]
I could think of several ways but one might be the easiest:

Adjust the yeelight.sh to not start from 0 but 1 and if 0 is given you iterate over all instances

**Comment by hphde** [comment]
@wowwood Changed with https://github.com/hphde/yeelight-shell-scripts/commit/8010f270ea5d9b57ec6428ae77d60063d7187cb6
