### ISSUE TITLE
Not imputing IPs correctly 

### ISSUE THREAD

**Issue by 1liminal1** [hphde/yeelight-shell-scripts#8]
Hi there, 

Im trying to set up your script, but clearly not putting the ips in correctly. 

Can you advise, it just says: "Now edit the yeelight.sh script and enter the IP address of each light you have separated by a space."

```
user@machine:/path/yeelight-shell-scripts$ ./yeelight-scene.sh 0 On
./yeelight.sh: line 2: Put: command not found
cat: ./192.168.190.105: No such file or directory
cat: 192.168.190.106: No such file or directory
cat: 192.168.190.112: No such file or directory
liminal@tautulli:/opt/Tautulli/script/yeelight-shell-scripts$
```

This is how I entered the IP;

```
eclare -a ID=($(cat $(dirname $0)/192.168.190.105 192.168.190.106 192.168.190.112))
```

Thanks

**Comment by hphde** [comment]
Good catch. I will adjust the setup - you need to edit `yeelight-ips`

from the comment in the script:
`# Put all your Yeelights separated by spaces in yeelight-ips`

**Comment by 1liminal1** [comment]
I found one of the forks that worked. Thanks

**Comment by 1liminal1** [comment]
Oh ok, can you give an example of how it should look please?

And thanks, this is just what im looking for,

**Comment by 1liminal1** [comment]
OH, Got it!!! 

Ill do it from scratch and try again lol, thanks!

**Comment by 1liminal1** [comment]
Working perfect, thanks again.
