### ISSUE TITLE
Wont execute script if full path? 

### ISSUE THREAD

**Issue by 1liminal1** [hphde/yeelight-shell-scripts#9]
Hi again, 

I seem to have an issue when running the script from the full path?

```
Executing on ID 1 [192.168.190.105] ...   1 Off
Executing on ID 2 [192.168.190.106] ...   2 Off
Executing on ID 3 [192.168.190.112] ...   3 Off
```
Returns this and does nothing

Where as running the script from the directory gives me;

```
Executing on ID 1 [192.168.190.105] ...   1 "method":"set_power","params":["off"]
Executing on ID 2 [192.168.190.106] ...   2 "method":"set_power","params":["off"]
Executing on ID 3 [192.168.190.112] ...   3 "method":"set_power","params":["off"]

```
And it works

**Comment by hphde** [comment]
What did you do exactly?

**Comment by 1liminal1** [comment]
Ok so my use case is to turn off and on some lights using Tautulli when I start or stop playback in Plex. for this to work I need to execute the script using the full path.

```
user@machine:~$ /opt/Tautulli/script/yeelight-shell-scripts/yeelight.sh 0 Off/opt/Tautulli/script/yeelight-shell-scripts/yeelight.sh 0 On
 ```
This does not work;

If I navigate to the directory and run the script as below; 
Works

```
user@machine:/opt/Tautulli/script/yeelight-shell-scripts$ ./yeelight-scene.sh 0 On
Executing on ID 1 [192.168.190.105] ...   1 "method":"set_power","params":["on"]
Executing on ID 2 [192.168.190.106] ...   2 "method":"set_power","params":["on"]
Executing on ID 3 [192.168.190.112] ...   3 "method":"set_power","params":["on"]
```
If I run it from the full path, I get a different output and it doesn't run.

```
user@machine:~$ /opt/Tautulli/script/yeelight-shell-scripts/yeelight.sh 0 On
Executing on ID 1 [192.168.190.105] ...   1 On
Executing on ID 2 [192.168.190.106] ...   2 On
Executing on ID 3 [192.168.190.112] ...   3 On
```

So it still runs, but there is something about the path that doesn't let it execute correctly?

**Comment by 1liminal1** [comment]
Right, sorry. I got confused with the script names

I have tested it and it seems to be working when I run "yeelight-scene.sh 0 On" not "yeelight.sh 0 On" 

Sorry to waste your time :)
